name: MT3Chained-Step3

on:
  push:
    branches:
      - main

env:
  APP_NAME: mt3chained-step3
  LOGIN_SERVER: acr29833937032923.azurecr.io

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check-out Repo 
        uses: actions/checkout@v2
        with:
          path: Chained/MT3Chained-Step3
      
      - name: Check-out MathTrickCore 
        uses: actions/checkout@v2
        with:
          repository: tbfichter/MathTrickCore
          path: MathTrickCore
          token: ${{ secrets.PAT_GITHUB }}

      # Connect to Azure Container Registry (ACR)
      - name: ACR login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.LOGIN_SERVER }}
          username: ${{ secrets.ACR_CLIENT_ID }}
          password: ${{ secrets.ACR_CLIENT_PASSWORD }}
      # Container build and push to a Azure Container Registry (ACR)
      - name: Build, tag, and push image to ACR
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Chained/MT3Chained-Step3/Dockerfile
          push: true
          tags: |
            ${{ env.LOGIN_SERVER }}/${{ env.APP_NAME }}:${{ github.run_number }}
            ${{ env.LOGIN_SERVER }}/${{ env.APP_NAME }}:latest
